### ISSUE TITLE
Not working with the latest version of impacket

### ISSUE THREAD

**Issue by rhertzog** [nccgroup/keimpx#21]
On a Kali system with python-impacket (0.9.18-0kali1), keimpx complains about the version of impacket due to import errors:
```
$ keimpx 
You need to install Python Impacket library first.
Get it from Core Security's Google Code repository:
sudo apt-get -y remove python-impacket # to remove the system-installed outdated version of the library
cd /tmp
svn checkout http://impacket.googlecode.com/svn/trunk/ impacket
cd impacket
python setup.py build
sudo python setup.py install
```

keimpx has not evolved for a long time and is not working with the current version of impacket. Will you continue to maintain keimpx or shall we consider it abandoned ?

This ticket is prompted by https://bugs.kali.org/view.php?id=4007

**Comment by NEXUS2345** [comment]
Hi @rhertzog,

I've recently taken over maintenance of keimpx and it is now working with Impacket version 0.9.20. Please advise if you need me to do anything in order to get keimpx added back into Kali.

Thank you,
NEXUS2345

**Comment by rhertzog** [comment]
Hi, the tool will not be added back until it works with Python 3. Kali is currently getting rid of Python 2. See https://gitlab.com/kalilinux/internal/roadmap/issues/27

Feel to open a ticket in bugs.kali.org once the application is ready to be re-introduced.

**Comment by NEXUS2345** [comment]
@rhertzog at this time Impacket is only rated as compatible with Python 3.6. As such, I am proceeding with porting keimpx to Python 3.6 with backwards compatibility for 2.7. Will this be a problem?

**Comment by rhertzog** [comment]
@NEXUS2345 Well, Kali has python 3.7 as default and Debian is currently switching to Python 3.8 as default so we're going to do the same process. So 3.6 is fine as long as it also work on 3.7 and 3.8. And AFAIK we don't have any report of impacket not working with python 3.7.

**Comment by NEXUS2345** [comment]
Hi @rhertzog, keimpx is now working with Python 3.7.6, but not yet 3.8 as impacket haven't released a new version with support yet. As such, I'm closing this issue now and will be opening a ticket on bugs.kali.org.
